source 'https://rubygems.org'

gem 'rails', '3.2.1'
gem 'rake'

gem 'sqlite3'

gem 'slim'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'compass-rails'
end

gem 'jquery-rails'

gem 'simple_form', '1.5.2'
# gem 'inherited_resources'
# gem 'draper'

gem 'premailer'
gem 'mail_view'

group :development, :test do
  gem 'rspec-rails'
  gem 'spork-rails'
  gem 'cucumber-rails'
  gem 'jasmine'
  gem 'pry'
  gem 'ruby-debug19', :require => 'ruby-debug'
end

group :test do
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'selenium-webdriver', '= 2.14.0'
  gem 'email_spec'
end