source 'https://rubygems.org'

gem 'rails'
gem 'rake'

gem 'sqlite3'

gem 'slim'

group :assets do
  gem 'sass-rails'
  gem 'compass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

gem 'simple_form'

group :development, :test do
  gem 'rspec-rails'
  gem 'spork-rails'
  gem 'cucumber-rails', :require => false
  gem "konacha"
  gem 'pry'
end

group :test do
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'selenium-webdriver', '= 2.14.0'
  gem 'specjour', :git => 'https://github.com/garmz/specjour', :branch => 'fix-rspec-issues'
end


