source "http://rubygems.org"

gem "rspec-core", :path => "../../rspec-core"
gem "rspec-expectations", :path => "../../rspec-expectations"
gem "rspec-mocks", :path => "../../rspec-mocks"

gem "ruby-debug"
gem "guard-rspec"
