source ~/.bash/aliases
source ~/.bash/completions
source ~/.bash/exports

[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad