" Hide toolbar and menubar.
set guioptions-=T
set guioptions-=m

" Font.
set guifont=Monaco:h12

" Scrollbars
set guioptions-=L
set guioptions-=r

" Turn off blinking in normal mode
set gcr=n:blinkon0

