" Configure
runtime config/bundles.vim
runtime config/settings.vim
runtime config/plugins.vim
runtime config/commands.vim
runtime config/autocmd.vim
runtime config/mappings.vim
runtime config/gui.vim

if filereadable(glob(".vimrc.local"))
    source .vimrc.local
endif
