" Pathogen
call pathogen#infect()

" Configure
runtime config/settings.vim
runtime config/plugins.vim
runtime config/functions.vim
runtime config/commands.vim
runtime config/autocmd.vim
runtime config/mappings.vim

if has("gui_running")
  runtime config/gui.vim
endif

