source $HOME/.zsh/env
source $HOME/.zsh/theme
source $HOME/.zsh/aliases
source $HOME/.zsh/rbenv

for file in $HOME/.zsh/plugins/**/*; do
  source $file
done

[ -f .zshrc.local ] && source .zshrc.local
