source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'paperclip', '2.3.3'
gem 'will_paginate', '3.0.pre2'
gem 'active_record_defaults'

gem 'sprockets'
gem 'sprocketizer', :git => "git://github.com/garmz/sprocketizer.git"
gem 'yui-compressor'
gem 'compass'

# gem 'hoptoad_notifier'
# gem 'newrelic_rpm'

group :development do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'capistrano'
  gem 'autotest'
  gem 'rspec-rails'
end

group :test do
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'capybara', '0.3.9'
  gem 'selenium-webdriver', '0.0.24'
  gem 'webrat'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'autotest'
  gem 'rspec-rails'
  gem 'rcov'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'ZenTest'
  gem 'autotest-notification'
end
