<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--require features/support/env.rb --require features/step_definitions --format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip --tags ~@pending"
wip_opts = "--require features/support/env.rb --require features/step_definitions --format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags @wip:3"
%>
default: <%= std_opts %> features
wip: <%= wip_opts %> features
no-js: <%= std_opts %> --tags ~@javascript
js: <%= std_opts %> --tags @javascript
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip